### ISSUE TITLE
/searchjob failed with the error “dispatch_failed”

### ISSUE THREAD

**Issue by ghost** [f-lab-edu/employbot#1]
슬래시 커맨드 `/searchjob`을 생성 후 발생한 오류

다음과 같이 `SlackAPI.py`에 메세지 포스팅 메서드를 생성하고

```py
    def post_message(self, channel_id, text):
        """
        ### 슬랙 채널 내 메세지 포스팅
        - parameter : `channel_id`, `text`
        - return : `result`
        """
        result = self.client.chat_postMessage(
            channel = channel_id,
            text = text,
        )
        return result
```

`FastAPI` 파일에서 이 메서드를  사용해  직업 검색 사이트 안내 기능을 구현

```py
@app.post("/searchjob")
async def search_job():
    slack_client = SlackAPI(token=slack_tokens.BOT_TOKEN)
    search_text = """
    - 잡코리아 : https://www.jobkorea.co.kr
    - 사람인 : https://www.saramin.co.kr/
    - 원티드 : https://www.wanted.co.kr/
    """
    result = slack_client.post_message(slack_tokens.CHANNEL_ID, text=search_text)

    return "result"

```

했으나 슬랙에서 아래와 같이 문구가 발생

<img width="408" alt="Screenshot 2023-09-18 at 21 47 40" src="https://github.com/f-lab-edu/employbot/assets/55238671/9e96ba7e-6aad-423d-9c11-eafdb84818a4">

**Comment by issamansur** [comment]
maybe
```
return result```
instead of 
```
return "result"
```

**Comment by issamansur** [comment]
I think u have endpoint that was unreachable. So it was returning this message. You can fix that, by using ngrok for tunnel.

**Comment by issamansur** [comment]
Try also use simple search_text

**Comment by ghost** [comment]
> I think u have endpoint that was unreachable. So it was returning this message. You can fix that, by using ngrok for tunnel.

Thank you @issamansur.

Thanks to you, I solved the problem.

If you have one more question, Is there any way to continue using the ngrok url? I signed up for the site and received a token to use it, but I need to update the URL.

**Comment by issamansur** [comment]
I think u need to restart ngrok. So u can get a new URL for using. Take note that ngrok URLs are temporary and change each time you restart the tunnel. If you need a more stable URL, consider using advanced ngrok plans or alternative tunneling services that provide more persistent URLs.
